
services:
    web:
        container_name: web
        build:
            context: ./Web
            dockerfile: Dockerfile
            target: dev
        ports:
            - "5173:5173"
        volumes:
            - ./Web:/app
            - /app/node_modules     # Ignore node_modules

    api:
        build:
            context: ./Api
            dockerfile: Dockerfile.dev
        ports:
            - "8080:8080"
        volumes:
            - ./Api:/Api
        environment:
            - ConnectionStrings__Default=Server=localhost;Database=BrokeManagerDb;User Id=sa;Password=Password123!;TrustServerCertificate=True;
            - JWT_KEY=RqlaOEhJIQ9zp4roP9toyghzBapubY1y
        depends_on:
            - database

    database:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sql_server
        platform: linux/amd64   # Force x86_64 emulation for ARM hosts
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=${MICROSOFT_SQL_PASSWORD}
        volumes:
            - mssql_data:/var/opt/mssql # Damit deine Daten nicht weg sind, wenn der Container stoppt

    migrator:
        image: mcr.microsoft.com/dotnet/sdk:8.0 # Wir brauchen das SDK für die Tools
        container_name: ef_migrator
        volumes:
            - ./Api:/src 
        working_dir: /src
        environment:
            - ConnectionStrings__DefaultConnection=Server=database;Database=BrokeManagerDb;User Id=sa;Password=${MICROSOFT_SQL_PASSWORD};TrustServerCertificate=True;
        command: >
            bash -c "dotnet tool install --global dotnet-ef &&
            export PATH=\"$$PATH:/root/.dotnet/tools\" &&
            dotnet restore &&
            dotnet ef database update"
        depends_on:
            - database

volumes:
    mssql_data:
