POST http://localhost:5180/transactions
Content-Type: application/json

{
    "amount": 25,
    "type": "Expense",
    "date": "2026-05-17",
    "title": "asd",
    "Description": "wir warne essne",
    "CounterParty": "Essen"
}